FROM maven:3.6.3-openjdk-11

WORKDIR /app

COPY src /app/src
COPY lib /app/lib
COPY .mvn /app/.mvn
COPY mvnw /app/mvnw
COPY pom.xml /app/pom.xml
COPY target /app/target

CMD [ "mvn", "spring-boot:run" ]
