# pull official base image
FROM node:14.16.0-alpine

# set working directory
WORKDIR /app

# add `/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
RUN yarn
# RUN yarn add react-scripts@3.4.1 -g --silent
RUN yarn global add serve

# add app
COPY ./frontend/ ./

# start app
CMD yarn && yarn build && serve -s build
