FROM maven:3.6.3-openjdk-11

WORKDIR /app

COPY src /app/src
COPY lib /app/lib
COPY .mvn /app/.mvn
COPY mvnw /app/mvnw
COPY pom.xml /app/pom.xml
#COPY target /app/target
COPY .env /app/.env

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD [ "mvn", "--no-transfer-progress", "spring-boot:run" ]
